
plugins {
  id 'tripleo.elijah.java-conventions'
}

repositories {
  gradlePluginPortal()
//    maven {url "https://plugins.gradle.org/m2"}
  mavenCentral()
  mavenLocal()
}

dependencies {

  testRuntimeOnly    'org.junit.jupiter:junit-jupiter-engine:5.10.0'
//  testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
  testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.0'
  testImplementation 'org.assertj:assertj-core:3.24.2'
}

test {
  useJUnitPlatform()
}

java {
  sourceCompatibility = JavaVersion.VERSION_17
  targetCompatibility = JavaVersion.VERSION_17
}

description = 'model-status'
version = 'elevated-potential.2023.5'
