//import java.time.LocalDateTime
//import java.time.format.DateTimeFormatter

plugins {
  id 'tripleo.elijah.java-conventions'
  //id "io.ktor.plugin" version "2.3.4"
  //id "org.xtext.xtend" version "4.0.0"
}

repositories {
  gradlePluginPortal()
//    maven {url "https://plugins.gradle.org/m2"}
  mavenCentral()
  mavenLocal()
}

dependencies {
/*
  implementation 'org.clojure:clojure:1.12.4'
  implementation 'org.clojure:core.specs.alpha:0.2.56'
  implementation 'org.clojure:spec.alpha:0.2.194'

  implementation 'tripleo.elijah:elijah-core-api:2023.elevated-potential.7f'

  api 'io.reactivex.rxjava3:rxjava:3.1.6'
  api 'org.reactivestreams:reactive-streams:1.0.4'
  api 'commons-codec:commons-codec:1.15'
  api 'antlr:antlr:2.7.7'
*/

  testRuntimeOnly    'org.junit.jupiter:junit-jupiter-engine:5.10.0'
//  testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
  testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.0'
  testImplementation 'org.assertj:assertj-core:3.24.2'

  // http://xtext.github.io/xtext-gradle-plugin/xtend.html
  // https://stackoverflow.com/questions/23796404/could-not-find-method-compile-for-arguments-gradle
  //implementation 'org.eclipse.xtend:org.eclipse.xtend.lib:2.30.0'
}

test {
  useJUnitPlatform()
}

java {
  sourceCompatibility = JavaVersion.VERSION_17
  targetCompatibility = JavaVersion.VERSION_17
}

description = 'model-status'
version = 'elevated-potential.2023.5'
